### PR TITLE
fixed parsing

### LINKED ISSUE #33: Parsing "éclatax"
Apparemment le parsing est "éclatax" selon les dire de son créateur.

### PR DESCRIPTION
**Pull request by gd-harco**
- Add handling of whitespace in line before the info it contains
- Added handling for space between color value + Added easter eggs error message
- Fixed parsing error caused by withespace after a texture path.
- Added security for duplicate textures path

### CODE REVIEW

**Comment by gd-harco** [comment]
@BenoitRoux0 still awaiting your review

**Comment by BenoitRoux0** [comment]
`F 20,20t,20`
work

**Comment by BenoitRoux0** [comment]
`F ,20,20t,20`
work

**Comment by BenoitRoux0** [comment]
`F ,,,20,20t,20`
work

**Comment by gd-harco** [comment]
@BenoitRoux0 supposedly fixed with new push in both mandatory and bonus part

**Comment by BenoitRoux0** [comment]
[maps.zip](https://github.com/BenoitRoux0/cub3D/files/12744064/maps.zip)

maps to test with assets sent on signal

**Comment by gd-harco** [comment]
@BenoitRoux0 Should be good to review now !

**Comment by gd-harco** [comment]
@BenoitRoux0 please merge this one before #39

**Review by BenoitRoux0 — APPROVED** [review]

**Comment by BenoitRoux0** [comment]
sorry

**Pull request merged**
